import dotenv from 'dotenv';

dotenv.config();

export const {
  PORT,
  REACT_APP_SPOTIFY_CLIENT_ID,
  REACT_APP_SPOTIFY_CLIENT_SECRET,
  REACT_APP_SPOTIFY_REDIRECT_URI,
  MYSQL_USER,
  MYSQL_PW,
  MYSQL_HOST,
  MYSQL_NAME,
  REACT_APP_GOOGLE_CLIENT_ID,
  REACT_APP_GOOGLE_CLIENT_SECRET,
  REACT_APP_GOOGLE_REDIRECT_URI,
  SESSION_SECRET,
  COOKIE_SECRET
} = process.env;


export default {
  PORT,
  SPOTIFY_CLIENT_ID: REACT_APP_SPOTIFY_CLIENT_ID,
  SPOTIFY_CLIENT_SECRET: REACT_APP_SPOTIFY_CLIENT_SECRET,
  SPOTIFY_REDIRECT_URI: REACT_APP_SPOTIFY_REDIRECT_URI,
  MYSQL_USER,
  MYSQL_PW,
  MYSQL_HOST,
  MYSQL_NAME,
  GOOGLE_CLIENT_ID: REACT_APP_GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: REACT_APP_GOOGLE_CLIENT_SECRET,
  GOOGLE_REDIRECT_URI: REACT_APP_GOOGLE_REDIRECT_URI,
  SESSION_SECRET,
  COOKIE_SECRET
};
